import { useState } from 'react'
import { createBook } from '../storage.js'
import '../styles/Cart.css'
const blankForm = { title: '', author: '', pages: '', genre: '', purchaseStatus: 'planned', plannedPurchaseDate: '', arrivalDate: '' }
function Cart({ library, onAddBook, onUpdateBook, onRemoveBook }) {
  const [form, setForm] = useState(blankForm); const [showForm, setShowForm] = useState(false); const wishlist = library.filter((book) => book.status === 'wishlist').sort((a, b) => a.shelfOrder - b.shelfOrder); const change = (event) => setForm({ ...form, [event.target.name]: event.target.value })
  function addToWishlist(event) { event.preventDefault(); if (!form.title.trim() || !form.author.trim() || Number(form.pages) <= 0) return; onAddBook(createBook(form.title, form.author, Number(form.pages), form.genre, 'wishlist', form)); setForm(blankForm); setShowForm(false) }
  return <div className='cart-page'><header className='cart-header'><div><p className='eyebrow'>Your next picks</p><h1>Shopping List</h1><p>Books you want to buy, kept on their own little shelf.</p></div><button className='primary-button' onClick={() => setShowForm((shown) => !shown)}>{showForm ? 'Close' : '+ Add a book'}</button></header>
    {showForm && <form className='cart-form' onSubmit={addToWishlist}><input required name='title' value={form.title} onChange={change} placeholder='Book title' /><input required name='author' value={form.author} onChange={change} placeholder='Author' /><input required min='1' type='number' name='pages' value={form.pages} onChange={change} placeholder='Pages' /><input name='genre' value={form.genre} onChange={change} placeholder='Genre' /><label>Shopping status<select name='purchaseStatus' value={form.purchaseStatus} onChange={change}><option value='planned'>Planning to buy</option><option value='ordered'>Ordered</option><option value='arrived'>Arrived</option></select></label><label>Planned purchase<input type='date' name='plannedPurchaseDate' value={form.plannedPurchaseDate} onChange={change} /></label><label>Arrival date<input type='date' name='arrivalDate' value={form.arrivalDate} onChange={change} /></label><button className='submit-button'>Add to list</button></form>}
    <section className='shopping-shelf'><div className='shelf-header'><h2>On your shopping shelf</h2><span>{wishlist.length} books</span></div><div className='cart-list'>{wishlist.length === 0 ? <div className='empty-cart'>Your shopping shelf is clear. Add a book you want to buy.</div> : wishlist.map((book) => <article className='cart-item' key={book.id}><div className='cart-book'><span className='cart-spine' /><div><strong>{book.title}</strong><p>{book.author}</p><small>{book.genre || 'General'} · {book.pages} pages</small></div></div><div className='cart-details'><label>Status<select value={book.purchaseStatus} onChange={(e) => onUpdateBook(book.id, { purchaseStatus: e.target.value })}><option value='planned'>Planning to buy</option><option value='ordered'>Ordered</option><option value='arrived'>Arrived</option></select></label>{book.plannedPurchaseDate && <span>Buy: {book.plannedPurchaseDate}</span>}{book.arrivalDate && <span>Arrives: {book.arrivalDate}</span>}</div><div className='cart-actions'><button className='mini-button' onClick={() => onRemoveBook(book.id)}>Remove</button><button className='action-button' onClick={() => onUpdateBook(book.id, { status: 'tbr' })}>Bought → TBR</button></div></article>)}</div></section>
  </div>
}
export default Cart
